### ISSUE TITLE
iframe/video resize issue when loading data with .innerHTML =

### ISSUE THREAD

**Issue by JasonHoku** [BOTOOM/quill-resize-module#10]
Thank you for this seamless and quick media resize module on quill. 

I would like to report an issue with not being able to resize iframe/video when using .innerHTML to propagate Quill. 

This is what the code looks like after using embed video, and then saving and loading the content:

```<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/xyz?showinfo=0" width="677" height="392" style="float: right;"></iframe>```

But the element is not resizable. 

I hope this issue report is helpful to find a fix, or do you know of any quick fix to this?

A thousand thank yous in advance,
 Jason

**Comment by BOTOOM** [comment]
Hi @JasonHoku.

Thank you for contacting me, could you provide me more details about the error?

Can't it be resized again using the tools provided by the library or if you are trying to resize it by code?

I would appreciate if you could give me more details of the implementation so I can do my best to give you an answer.

**Comment by JasonHoku** [comment]
Thank you for your prompt response, @BOTOOM.

Allow me to clarify:

## Description of issue:

After embedding a YouTube video iframe, saving and then loading data (I use `.html = data` to preserve styles which are lost with `value = {data}`) into Quill, the video iframe element no longer has the resize options provided by this Quill module.

## Steps to reproduce:

Add video to Quill
Save Quill data to database
Load data into quill with `.html = data`
Notice the ability to resize is now gone and video must be re-added if desiring resize.

## Hypothesis:

Adding styles to iframe makes quill-resize-module not detect iframe element?
Possibly setting `.html = data` skips a procedural check for iframe videos by quill-resize-module?
_Not exactly sure though._


I hope this helps. Thank you again.

**Comment by BOTOOM** [comment]
Hello @JasonHoku 

I did a test with a nextjs project to recreate the error you are talking about, you can access here the code of the project:
https://github.com/BOTOOM/next_and_quill/blob/9b74059f7d5beb00ef9eb9848d72bdadae92d80d/components/RichTextArea.tsx#L37

this is the rendered result
![image](https://user-images.githubusercontent.com/28914781/146049849-473a964c-ef7a-4bfb-a18a-c5bfcc4b8fd3.png)

And even the tools of the library are shown.
![image](https://user-images.githubusercontent.com/28914781/146049911-5917b7ca-8931-4061-868c-aba497b62e34.png)


Could you provide me how are you implementing the editor, and how are you implementing the innerHTML?

**Comment by BOTOOM** [comment]
Issue closed for 10 days with no response.
